import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";

const root=path.resolve(import.meta.dirname,"..");
const sourcePath=path.join(root,"data","source","kbo_2025_pitcher_abilities.csv");
const ratingColumns=["pitcher_velocity","pitcher_stuff","pitcher_command","pitcher_movement","pitcher_stamina","pitcher_pitchability","pitcher_strikeout","pitcher_walk_control","pitcher_composure","pitch_four_seam","pitch_sinker","pitch_cutter","pitch_changeup","pitch_slider","pitch_curve","pitch_splitter","pitch_sweeper","pitch_knuckleball"];
const metadata={pitcher_repertoire:"TEXT",pitcher_source_level:"TEXT",pitcher_confidence:"TEXT",pitcher_formula_version:"TEXT",pitcher_sample_tbf:"INTEGER",pitcher_sample_ip:"REAL",pitcher_avg_velocity:"REAL",pitcher_k_stuff_plus:"REAL",pitcher_k_location_plus:"REAL",pitcher_whiff_rate:"REAL",pitcher_csw_rate:"REAL",pitcher_k_rate:"REAL",pitcher_bb_rate:"REAL",pitcher_hr_rate:"REAL",pitcher_fip:"REAL",pitcher_pitch_detail_json:"TEXT",pitcher_tracking_source_url:"TEXT"};
function parseCsv(text){const records=[];let record=[],field="",quoted=false;for(let i=0;i<text.length;i+=1){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i+=1;}else if(c==='"')quoted=false;else field+=c;}else if(c==='"')quoted=true;else if(c===","){record.push(field);field="";}else if(c==="\n"){record.push(field.replace(/\r$/, ""));if(record.some(Boolean))records.push(record);record=[];field="";}else field+=c;}if(field||record.length){record.push(field.replace(/\r$/, ""));records.push(record);}const headers=records.shift().map((v)=>v.replace(/^\uFEFF/,""));return records.map((values)=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??""])));}
const nullable=(value)=>String(value??"").trim()===""?null:Number(value);
const delta=(saveId,playerId,column)=>crypto.createHash("sha256").update(`${saveId}:${playerId}:${column}`).digest()[0]%5-2;
const abilities=parseCsv(fs.readFileSync(sourcePath,"utf8"));
const savesDb=new DatabaseSync(path.join(root,"data","kbo_fm_saves.db"),{readOnly:true});const saves=savesDb.prepare("SELECT id,base_team,player_db_path FROM game_saves WHERE player_db_path IS NOT NULL").all();savesDb.close();
let databases=0,updatedPlayers=0;
for(const save of saves){const target=path.resolve(save.player_db_path);if(!fs.existsSync(target))continue;const db=new DatabaseSync(target);try{const existing=new Set(db.prepare("PRAGMA table_info(players)").all().map((row)=>row.name));for(const column of ratingColumns){if(!existing.has(column))db.exec(`ALTER TABLE players ADD COLUMN ${column} INTEGER`);}for(const [column,type] of Object.entries(metadata)){if(!existing.has(column))db.exec(`ALTER TABLE players ADD COLUMN ${column} ${type}`);}const players=new Map(db.prepare("SELECT id,kbo_player_id,team,age FROM players WHERE position_group='P'").all().map((p)=>[String(p.kbo_player_id),p]));const columns=[...ratingColumns,...Object.keys(metadata)];const update=db.prepare(`UPDATE players SET ${columns.map((column)=>`${column}=?`).join(",")},salary=COALESCE(?,salary),ability_source_level=?,ability_formula_version=? WHERE id=?`);db.exec("BEGIN IMMEDIATE");let count=0;try{for(const row of abilities){const player=players.get(String(row.kbo_player_id));if(!player)continue;const values=ratingColumns.map((column)=>{const raw=nullable(row[column]);if(raw===null)return null;const adjusted=player.team!==save.base_team&&Number(player.age)<30?raw+delta(save.id,player.id,column):raw;return Math.max(1,Math.min(20,adjusted));});values.push(row.repertoire,row.source_level,row.confidence,row.formula_version,nullable(row.sample_tbf),nullable(row.sample_ip),nullable(row.avg_velocity),nullable(row.k_stuff_plus),nullable(row.k_location_plus),nullable(row.whiff_rate),nullable(row.csw_rate),nullable(row.k_rate),nullable(row.bb_rate),nullable(row.hr_rate),nullable(row.fip),row.pitch_detail_json,row.tracking_source_url,nullable(row.salary_10k_krw),row.source_level,row.formula_version,player.id);count+=Number(update.run(...values).changes);}if(count!==319)throw new Error(`Save ${save.id}: updated ${count}/319`);db.exec("COMMIT");}catch(error){db.exec("ROLLBACK");throw error;}databases+=1;updatedPlayers+=count;}finally{db.close();}}
console.log(`COMPLETE databases=${databases} pitchers=${updatedPlayers}`);
